version: '3.8'

networks:
  app4-network:

volumes:
  app4-mysql8_data_volume:


services:
  # nginx
  nginx-service:
    image: nginx:stable-alpine
    container_name: app4-nginx-container
    ports:
      - "8007:80"
    volumes:
      - ./:/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php81-service
      - mysql8-service
    links:
      - "php81-service:php-fpm"
    networks:
      - app4-network

  # php
  php81-service:
    image: foxmark/php8.2.12-fpm
    container_name: app4-php81-container
    ports:
      - "9000:9000"
    volumes:
      - ./:/app
      - ./docker/php/config/99-php.ini:/usr/local/etc/php/conf.d/99-php.ini
    networks:
      - app4-network

  # mysql
  mysql8-service:
    image: mysql:8.0
    container_name: app4-mysql8-container
    ports:
      - "3309:3306"
    volumes:
      - app4-mysql8_data_volume:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: secret
    networks:
      - app4-network
