version: '3.8'

networks:
  app-network:
    name: ${APP_NAME}-network

volumes:
  mysql8_data_volume:
      name: ${APP_NAME}-mysql8_data_volume


services:
  # nginx
  nginx-service:
    image: nginx:stable-alpine
    container_name: ${APP_NAME}-nginx-container
    ports:
      - "${HOST_PORT}:80"
    volumes:
      - ./:/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php81-service
      - mysql8-service
    links:
      - "php81-service:php-fpm"
    networks:
      - app-network

  # php
  php81-service:
    image: foxmark/php8.2.12-fpm:1.0
    container_name: ${APP_NAME}-php81-container
    # to add whole env file
    # env_file:
    #   - .env
    ports:
      - "9000:9000"
    volumes:
      - ./:/app
      - ./docker/php/config/99-php.ini:/usr/local/etc/php/conf.d/99-php.ini
    networks:
      - app-network

  # mysql
  mysql8-service:
    image: mysql:8.0
    container_name: ${APP_NAME}-mysql8-container
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - mysql8_data_volume:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    # bith set in .env file - therefor no value set!
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_PASSWORD
    networks:
      - app-network
